"""
StreamForge - Database Module
==============================
Area 2: Database / Storage

Purpose:
    Stores raw truck telemetry, windowed (5-min rolling avg) aggregates,
    and alerts generated by the stream processing layer (Faust/Bytewax).

Tech choice:
    PostgreSQL (with optional TimescaleDB extension for time-series
    performance) + SQLAlchemy ORM. TimescaleDB is a drop-in Postgres
    extension, so this module works with plain Postgres too — just skip
    the hypertable creation step if you don't have the extension.

Install:
    pip install sqlalchemy psycopg2-binary
"""

from datetime import datetime
from contextlib import contextmanager

from sqlalchemy import (
    create_engine, Column, Integer, String, Float, DateTime, ForeignKey, Index
)
from sqlalchemy.orm import declarative_base, sessionmaker, relationship

# ---------------------------------------------------------------------------
# 1. Connection setup
# ---------------------------------------------------------------------------

DATABASE_URL = "postgresql+psycopg2://streamforge:password@localhost:5432/streamforge_db"

engine = create_engine(DATABASE_URL, pool_size=20, max_overflow=10, pool_pre_ping=True)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)
Base = declarative_base()


# ---------------------------------------------------------------------------
# 2. Models
# ---------------------------------------------------------------------------

class Truck(Base):
    """Fleet vehicle registry — one row per truck."""
    __tablename__ = "trucks"

    id = Column(Integer, primary_key=True)
    truck_code = Column(String(50), unique=True, nullable=False, index=True)
    region = Column(String(100))
    registered_at = Column(DateTime, default=datetime.utcnow)

    telemetry = relationship("TelemetryRaw", back_populates="truck")
    aggregates = relationship("WindowedAggregate", back_populates="truck")
    alerts = relationship("Alert", back_populates="truck")


class TelemetryRaw(Base):
    """Raw sensor readings ingested from Kafka (pre-aggregation)."""
    __tablename__ = "telemetry_raw"

    id = Column(Integer, primary_key=True)
    truck_id = Column(Integer, ForeignKey("trucks.id"), nullable=False)
    temperature = Column(Float, nullable=False)
    event_timestamp = Column(DateTime, nullable=False)  # timestamp from the device
    ingested_at = Column(DateTime, default=datetime.utcnow)  # arrival time (server)

    truck = relationship("Truck", back_populates="telemetry")

    __table_args__ = (
        Index("ix_telemetry_truck_time", "truck_id", "event_timestamp"),
    )


class WindowedAggregate(Base):
    """Output of Faust/Bytewax 5-minute tumbling/hopping window jobs."""
    __tablename__ = "windowed_aggregates"

    id = Column(Integer, primary_key=True)
    truck_id = Column(Integer, ForeignKey("trucks.id"), nullable=False)
    window_start = Column(DateTime, nullable=False)
    window_end = Column(DateTime, nullable=False)
    avg_temperature = Column(Float, nullable=False)
    sample_count = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    truck = relationship("Truck", back_populates="aggregates")

    __table_args__ = (
        Index("ix_agg_truck_window", "truck_id", "window_start"),
    )


class Alert(Base):
    """Anomaly / threshold breach alerts (e.g., temp out of safe range)."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True)
    truck_id = Column(Integer, ForeignKey("trucks.id"), nullable=False)
    alert_type = Column(String(50), nullable=False)   # e.g. "HIGH_TEMP", "SENSOR_DROPOUT"
    severity = Column(String(20), default="WARNING")  # INFO / WARNING / CRITICAL
    message = Column(String(255))
    triggered_at = Column(DateTime, default=datetime.utcnow)
    resolved = Column(Integer, default=0)  # 0 = open, 1 = resolved

    truck = relationship("Truck", back_populates="alerts")


# ---------------------------------------------------------------------------
# 3. Session helper
# ---------------------------------------------------------------------------

@contextmanager
def get_session():
    """Context-managed session — commits on success, rolls back on error."""
    session = SessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


# ---------------------------------------------------------------------------
# 4. Init (create tables + optional TimescaleDB hypertables)
# ---------------------------------------------------------------------------

def init_db(use_timescaledb: bool = False):
    Base.metadata.create_all(bind=engine)

    if use_timescaledb:
        # Convert high-volume tables into TimescaleDB hypertables for
        # efficient time-partitioned storage/queries at IoT scale.
        with engine.connect() as conn:
            conn.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")
            conn.execute(
                "SELECT create_hypertable('telemetry_raw', 'event_timestamp', "
                "if_not_exists => TRUE);"
            )
            conn.execute(
                "SELECT create_hypertable('windowed_aggregates', 'window_start', "
                "if_not_exists => TRUE);"
            )


# ---------------------------------------------------------------------------
# 5. Repository functions (used by Faust/Bytewax workers and FastAPI layer)
# ---------------------------------------------------------------------------

def insert_telemetry(truck_code: str, temperature: float, event_timestamp: datetime):
    """Called by the Kafka consumer / Faust agent for every raw event."""
    with get_session() as session:
        truck = session.query(Truck).filter_by(truck_code=truck_code).first()
        if not truck:
            truck = Truck(truck_code=truck_code)
            session.add(truck)
            session.flush()  # get truck.id before using it below

        record = TelemetryRaw(
            truck_id=truck.id,
            temperature=temperature,
            event_timestamp=event_timestamp,
        )
        session.add(record)
        return record.id


def insert_windowed_aggregate(truck_code: str, window_start: datetime,
                               window_end: datetime, avg_temperature: float,
                               sample_count: int):
    """Called at the close of each 5-minute Faust/Bytewax window."""
    with get_session() as session:
        truck = session.query(Truck).filter_by(truck_code=truck_code).first()
        if not truck:
            raise ValueError(f"Unknown truck: {truck_code}")

        agg = WindowedAggregate(
            truck_id=truck.id,
            window_start=window_start,
            window_end=window_end,
            avg_temperature=avg_temperature,
            sample_count=sample_count,
        )
        session.add(agg)
        return agg.id


def raise_alert(truck_code: str, alert_type: str, message: str, severity: str = "WARNING"):
    """Called when a windowed aggregate crosses a defined threshold."""
    with get_session() as session:
        truck = session.query(Truck).filter_by(truck_code=truck_code).first()
        if not truck:
            raise ValueError(f"Unknown truck: {truck_code}")

        alert = Alert(
            truck_id=truck.id,
            alert_type=alert_type,
            severity=severity,
            message=message,
        )
        session.add(alert)
        return alert.id


def get_recent_aggregates(truck_code: str, limit: int = 20):
    """Used by the FastAPI /trucks/{id}/history endpoint for the dashboard."""
    with get_session() as session:
        truck = session.query(Truck).filter_by(truck_code=truck_code).first()
        if not truck:
            return []
        return (
            session.query(WindowedAggregate)
            .filter_by(truck_id=truck.id)
            .order_by(WindowedAggregate.window_start.desc())
            .limit(limit)
            .all()
        )


if __name__ == "__main__":
    # Quick manual test
    init_db(use_timescaledb=False)
    insert_telemetry("TRK-001", 24.5, datetime.utcnow())
    insert_windowed_aggregate("TRK-001", datetime.utcnow(), datetime.utcnow(), 25.1, 30)
    raise_alert("TRK-001", "HIGH_TEMP", "Rolling avg exceeded 40°C threshold", "CRITICAL")
    print("Sample data inserted successfully.")
